# Generated by Django 3.1 on 2021-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210711_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
